"""Add start_ms and end_ms to claims

Revision ID: 8386e0b5d2c3
Revises: d69309411789
Create Date: 2026-07-25 01:10:24.240752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8386e0b5d2c3'
down_revision: Union[str, None] = 'd69309411789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
