"""add search_vector generated column and GIN index on analyses

Revision ID: ddd99e24670b
Revises: 703fd78f5018
Create Date: 2026-07-24 16:18:46.317141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddd99e24670b'
down_revision: Union[str, None] = '703fd78f5018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(original_text, ''))", persisted=True), nullable=True))
    op.create_index('ix_analyses_search_vector', 'analyses', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analyses_search_vector', table_name='analyses', postgresql_using='gin')
    op.drop_column('analyses', 'search_vector')
    # ### end Alembic commands ###
